# @title: Data Operations
# @description: Find and operate on data from devices with various filters
# @tags: data, find, filter, operations, search

"""
Analysis Example
Operate data from devices

Read information from a variable generated by devices,
run a simple calculation in real-time, and create a new variable with the output.

Instructions
To run this analysis you need to add a device token to the environment variables,
To do that, go to your device, then token and copy your token.
Go the the analysis, then environment variables,
type device_token on key, and paste your token on value
"""
from tagoio_sdk import Analysis, Device


def my_analysis(context, scope: list = None) -> str:
    # reads the value of account_token from the environment variable
    device_token = next(
        (item for item in context.environment if item["key"] == "device_token"), None
    )

    if not device_token:
        return print("Missing device_token environment variable")

    device = Device(params={"token": device_token["value"]})

    # create the filter options to get the data from TagoIO
    query_filter = {
        "variable": "temperature",
        "query": "last_item",
    }

    result_array = device.getData(queryParams=query_filter)

    # Check if the array is not empty
    if not result_array or not result_array[0]:
        return print("Empty Array")

    # query:last_item always returns only one value
    value = result_array[0]["value"]
    time = result_array[0]["time"]

    # print to the console at TagoIO
    print(f"The last record of the water_level is {value}. It was inserted at {time}")

    # Multiplies the water_level value by 2 and inserts it in another variable
    obj_to_save = {
        "variable": "temperature_double",
        "value": value * 2,
    }

    result = device.sendData(data=obj_to_save)
    print(result)


# The analysis token in only necessary to run the analysis outside TagoIO
Analysis(params={"token": "MY-ANALYSIS-TOKEN-HERE"}).init(my_analysis)
